### ISSUE TITLE
Futhark grammar does not handle attributes

### ISSUE THREAD

**Issue by athas** [Alhadis/language-etc#2]
```futhark
x + y
x + #[unsafe] y
```

For some reason, the `#[unsafe]` attribute seems to be treated as a line comment start.  I can't figure out what part of the grammar does this.

**Comment by Alhadis** [comment]
I don't believe attributes are even being highlighted. Aside from `[`, are there any other characters which are treated specially when they immediately follow a `#` symbol?

**Comment by athas** [comment]
No, the grammar precedes attributes, I think.  The `#` symbol is only otherwise used for constructors (`#foo`), which is also nothing like a line comment.

**Comment by Alhadis** [comment]
So, whitespace is required for `#` to behave like a comment?

**Comment by athas** [comment]
No, `#` is never a comment starter in Futhark.  Line comments are written with `-- `.

**Comment by Alhadis** [comment]
OH. Yeah, sorry, I see what you're referring to now. 😅 The `#` comments are being sourced from [this](https://github.com/Alhadis/language-etc/blob/682250c3d778f4e5be15d538d00361226305a34b/grammars/futhark.cson#L38), which includes a rule for tokenising `#` as line comments (because you wouldn't believe how many languages have this syntax in common).

I'll fix this, hold on.

**Comment by athas** [comment]
Thanks!
